name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: nightloewe1/elf-loader
        ref: main
        token: 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
        path: ../elf-loader
    - name: Build
      run: cargo build --verbose
